FROM node:20-bookworm

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY dist ./dist
COPY public ./public
COPY vite.config.ts ./

EXPOSE 3000

CMD ["pnpm", "start:staging", "--port", "3000"]